apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-app-cloud
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: digital-app-cloud
              key: db.password